## Introduction to Numpy

In [9]:
import pandas as pd

In [10]:
import numpy as np

In [12]:
variable = [2,3,5,7,11]

In [13]:
type([2,3,5,7,11])

list

In [11]:
#Create a one dimensional Array
prime_array= np.array([2,3,5,7,11])
print(prime_array)

[ 2  3  5  7 11]


In [14]:
type(prime_array)

numpy.ndarray

In [15]:
new_var = []
for i in variable:
    new_var.append(i*2)

In [16]:
print(new_var)

[4, 6, 10, 14, 22]


In [17]:
print(prime_array[2])

5


In [18]:
type(prime_array[0])

numpy.int32

In [19]:
#Create a two dimensional array
another_array = np.array([[1,2],[3,4],[5,6]])
print(another_array)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
#How to get 4 out of the array
another_array[1][1]

4

In [23]:
another_array[1,1]   #another way is to use ","

4

In [24]:
oned_array = np.array(range(0,100))

In [25]:
oned_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
oned_array[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
twod_array= np.array([[1,2,3,4],[5,6,7,8]])

In [32]:
twod_array.shape

(2, 4)

In [33]:
#Create a three-dimensional array
threeD_array = np.array([[[1,2,3,4],
                         [5,6,7,8]],
                         [[9,10,11,12],
                         [13,14,15,16]]])
print(threeD_array)
print(threeD_array.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)


In [34]:
alma_array = np.array([[1,2,3],[4,5,6]])

In [36]:
alma_array.shape         #shape of the array

(2, 3)

In [37]:
alma_array.ndim          #highest dimension of the array

2

In [38]:
alma_array = np.array([[1,2,3,4],[4,5,6,9]])
alma_array.shape 

(2, 4)

In [41]:
alma_array= np.array([[[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]],
                      [[1,2,3],[4,5,6]]])
print(alma_array.shape)

(4, 2, 3)


In [42]:
alma_array.size            #count of elements

24

In [43]:
alma_array.dtype            #data type

dtype('int32')

#### Changing th etypr using 'ndarray.astype

In [47]:
#Create an array
aravali= np.array([2,3,4])
print(aravali)
print(aravali.dtype)

#change the data type of the array to float
aravali_ =aravali.astype('float64')
print(aravali_)
print(aravali_.dtype)

#Change the data type of the array to string
_aravali_ =aravali.astype('string_')
print(_aravali_)
print(_aravali_.dtype)

[2 3 4]
int32
[2. 3. 4.]
float64
[b'2' b'3' b'4']
|S11
