In [5]:
l = [1,2,3]
l * 2.5

TypeError: can't multiply sequence by non-int of type 'float'

In [9]:
import numpy as np

np_l = np.array([1,2,3])

np_l * 2.5

array([2.5, 5. , 7.5])

In [10]:
np.array([1, "avc" , True])

array(['1', 'avc', 'True'], dtype='<U11')

In [11]:
list1=[1,4,6]
list2=[3,6,7]

list1+list2

[1, 4, 6, 3, 6, 7]

In [12]:
np_1 =np.array([1,4,6])
np_2 =np.array([3,6,7])
np_1 + np_2

array([ 4, 10, 13])

In [13]:
np.array(1.0, 2, 3.5, 0.2, True)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [14]:
np.array( [1.0, 2, 3.5, 0.2, "True"] )

array(['1.0', '2', '3.5', '0.2', 'True'], dtype='<U32')

In [15]:
np.array( [1.0, 2, 3.5, 0.2, True] )

array([1. , 2. , 3.5, 0.2, 1. ])

In [16]:

np.array[1.0, 2, 3.5, 0.2, True]

TypeError: 'builtin_function_or_method' object is not subscriptable